<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('data_types')->delete();
        
        DB::table('data_types')->insert(array (
            0 => 
            array (
                'controller' => '\\App\\Http\\Controllers\\Admin\\Voyager\\UserController',
                'created_at' => '2023-04-03 06:16:18',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Users',
                'display_name_singular' => 'User',
                'generate_permissions' => 1,
                'icon' => 'voyager-person',
                'id' => 1,
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'name' => 'users',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'server_side' => 0,
                'slug' => 'users',
                'updated_at' => '2023-05-02 04:53:16',
            ),
            1 => 
            array (
                'controller' => '',
                'created_at' => '2023-04-03 06:16:18',
                'description' => '',
                'details' => NULL,
                'display_name_plural' => 'Menus',
                'display_name_singular' => 'Menu',
                'generate_permissions' => 1,
                'icon' => 'voyager-list',
                'id' => 2,
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'name' => 'menus',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'menus',
                'updated_at' => '2023-04-03 06:16:18',
            ),
            2 => 
            array (
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerRoleController',
                'created_at' => '2023-04-03 06:16:18',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Roles',
                'display_name_singular' => 'Role',
                'generate_permissions' => 1,
                'icon' => 'voyager-lock',
                'id' => 3,
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'name' => 'roles',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'roles',
                'updated_at' => '2023-05-01 12:42:02',
            ),
            3 => 
            array (
                'controller' => '',
                'created_at' => '2023-04-03 06:16:20',
                'description' => '',
                'details' => NULL,
                'display_name_plural' => 'Categories',
                'display_name_singular' => 'Category',
                'generate_permissions' => 1,
                'icon' => 'voyager-categories',
                'id' => 4,
                'model_name' => 'TCG\\Voyager\\Models\\Category',
                'name' => 'categories',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'categories',
                'updated_at' => '2023-04-03 06:16:20',
            ),
            4 => 
            array (
                'controller' => '',
                'created_at' => '2023-04-03 06:16:20',
                'description' => '',
                'details' => NULL,
                'display_name_plural' => 'Posts',
                'display_name_singular' => 'Post',
                'generate_permissions' => 1,
                'icon' => 'voyager-news',
                'id' => 5,
                'model_name' => 'TCG\\Voyager\\Models\\Post',
                'name' => 'posts',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'server_side' => 0,
                'slug' => 'posts',
                'updated_at' => '2023-04-03 06:16:20',
            ),
            5 => 
            array (
                'controller' => '',
                'created_at' => '2023-04-03 06:16:20',
                'description' => '',
                'details' => NULL,
                'display_name_plural' => 'Pages',
                'display_name_singular' => 'Page',
                'generate_permissions' => 1,
                'icon' => 'voyager-file-text',
                'id' => 6,
                'model_name' => 'TCG\\Voyager\\Models\\Page',
                'name' => 'pages',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'pages',
                'updated_at' => '2023-04-03 06:16:20',
            ),
            6 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-03 10:55:35',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'National Chapters',
                'display_name_singular' => 'National Chapter',
                'generate_permissions' => 1,
                'icon' => 'voyager-world',
                'id' => 8,
                'model_name' => 'App\\Models\\NationalChapter',
                'name' => 'national_chapters',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'national-chapters',
                'updated_at' => '2023-04-11 06:05:24',
            ),
            7 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-03 12:44:46',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":"userMembers"}',
                'display_name_plural' => 'Members',
                'display_name_singular' => 'Member',
                'generate_permissions' => 1,
                'icon' => 'voyager-people',
                'id' => 9,
                'model_name' => 'App\\Models\\API\\Member',
                'name' => 'members',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'members',
                'updated_at' => '2023-05-10 09:52:38',
            ),
            8 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-11 09:26:07',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Countries',
                'display_name_singular' => 'Country',
                'generate_permissions' => 1,
                'icon' => 'voyager-data',
                'id' => 10,
                'model_name' => 'App\\Models\\Country',
                'name' => 'countries',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'countries',
                'updated_at' => '2023-04-12 05:11:51',
            ),
            9 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-11 09:55:10',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Member Roles',
                'display_name_singular' => 'Member Role',
                'generate_permissions' => 1,
                'icon' => 'voyager-lock',
                'id' => 11,
                'model_name' => 'App\\Models\\API\\Role',
                'name' => 'member_roles',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'member-roles',
                'updated_at' => '2023-04-11 10:03:19',
            ),
            10 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-13 08:01:33',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'News',
                'display_name_singular' => 'News',
                'generate_permissions' => 1,
                'icon' => 'voyager-news',
                'id' => 12,
                'model_name' => 'App\\Models\\News',
                'name' => 'news',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'news',
                'updated_at' => '2023-04-28 10:23:23',
            ),
            11 => 
            array (
                'controller' => '\\App\\Http\\Controllers\\Admin\\Voyager\\ContactMessageController',
                'created_at' => '2023-04-17 07:30:58',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Contact Messages',
                'display_name_singular' => 'Contact Message',
                'generate_permissions' => 1,
                'icon' => 'voyager-chat',
                'id' => 14,
                'model_name' => 'App\\Models\\ContactMessage',
                'name' => 'contact_messages',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'contact-messages',
                'updated_at' => '2023-04-18 11:21:56',
            ),
            12 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-17 12:48:22',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Abouts',
                'display_name_singular' => 'About',
                'generate_permissions' => 1,
                'icon' => 'voyager-info-circled',
                'id' => 15,
                'model_name' => 'App\\Models\\About',
                'name' => 'abouts',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'abouts',
                'updated_at' => '2023-04-18 04:58:06',
            ),
            13 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-18 05:40:25',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Concepts',
                'display_name_singular' => 'Concept',
                'generate_permissions' => 1,
                'icon' => 'voyager-file-text',
                'id' => 16,
                'model_name' => 'App\\Models\\Concept',
                'name' => 'concepts',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'concepts',
                'updated_at' => '2023-04-18 05:59:59',
            ),
            14 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-18 05:58:44',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Timelines',
                'display_name_singular' => 'Timeline',
                'generate_permissions' => 1,
                'icon' => 'voyager-lightbulb',
                'id' => 18,
                'model_name' => 'App\\Models\\Timeline',
                'name' => 'timelines',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'timelines',
                'updated_at' => '2023-04-18 06:18:45',
            ),
            15 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-25 10:38:56',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Faqs',
                'display_name_singular' => 'Faq',
                'generate_permissions' => 1,
                'icon' => 'voyager-question',
                'id' => 19,
                'model_name' => 'App\\Models\\Faq',
                'name' => 'faqs',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'faqs',
                'updated_at' => '2023-04-25 10:53:00',
            ),
            16 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-04-26 13:09:04',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Testimonials',
                'display_name_singular' => 'Testimonial',
                'generate_permissions' => 1,
                'icon' => 'voyager-bubble',
                'id' => 20,
                'model_name' => 'App\\Models\\Testimonial',
                'name' => 'testimonials',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'testimonials',
                'updated_at' => '2023-04-27 06:09:12',
            ),
            17 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-05-05 12:24:03',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'display_name_plural' => 'Role Members',
                'display_name_singular' => 'Role Member',
                'generate_permissions' => 1,
                'icon' => NULL,
                'id' => 21,
                'model_name' => 'App\\Models\\Api\\RoleMember',
                'name' => 'role_member',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'role-member',
                'updated_at' => '2023-05-05 12:24:03',
            ),
            18 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-05-19 11:09:29',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Opportunities',
                'display_name_singular' => 'Opportunity',
                'generate_permissions' => 1,
                'icon' => 'voyager-lightbulb',
                'id' => 22,
                'model_name' => 'App\\Models\\Opportunity',
                'name' => 'opportunities',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'opportunities',
                'updated_at' => '2023-06-05 08:20:38',
            ),
            19 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-06-05 14:58:13',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Board Secretariat members',
                'display_name_singular' => 'Board Secretariat member',
                'generate_permissions' => 1,
                'icon' => 'voyager-people',
                'id' => 24,
                'model_name' => 'App\\Models\\BoardMember',
                'name' => 'board_members',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'board-members',
                'updated_at' => '2023-06-05 15:23:29',
            ),
            20 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-06-05 15:31:51',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Board Secretariats',
                'display_name_singular' => 'Board Secretariat',
                'generate_permissions' => 1,
                'icon' => 'voyager-people',
                'id' => 25,
                'model_name' => 'App\\Models\\BoardSecretariat',
                'name' => 'board_secretariats',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'board-secretariats',
                'updated_at' => '2023-06-05 15:35:10',
            ),
            21 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-06-05 15:49:37',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Projects',
                'display_name_singular' => 'Project',
                'generate_permissions' => 1,
                'icon' => 'voyager-book',
                'id' => 26,
                'model_name' => 'App\\Models\\Project',
                'name' => 'projects',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'projects',
                'updated_at' => '2023-06-05 15:50:19',
            ),
            22 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-06-21 16:02:34',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'display_name_plural' => 'Event Categories',
                'display_name_singular' => 'Event Category',
                'generate_permissions' => 1,
                'icon' => 'voyager-categories',
                'id' => 27,
                'model_name' => 'App\\Models\\EventCategory',
                'name' => 'event_categories',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'event-categories',
                'updated_at' => '2023-06-21 16:02:34',
            ),
            23 => 
            array (
                'controller' => NULL,
                'created_at' => '2023-06-21 16:32:34',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Events',
                'display_name_singular' => 'Event',
                'generate_permissions' => 1,
                'icon' => 'voyager-calendar',
                'id' => 28,
                'model_name' => 'App\\Models\\Event',
                'name' => 'events',
                'policy_name' => NULL,
                'server_side' => 0,
                'slug' => 'events',
                'updated_at' => '2023-06-22 10:26:04',
            ),
        ));
        
        
    }
}