<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MembersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('members')->delete();

        DB::table('members')->insert(array (
            0 =>
            array (
                'id' => 1,
                'first_name' => 'Fuad',
                'email' => 'fuadbayramli94@gmail.com',
                'avatar' => 'members/April2023/MqNuP2YRd2VSKWyhP368.png',
                'email_verified_at' => NULL,
                'password' => '12345678',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 05:45:00',
                'updated_at' => '2023-04-04 08:58:46',
                'username' => 'fuadbayramli',
                'nam_youth_email' => 'fuadbayramli94@gmail.com',
                'last_name' => 'Bayramli',
                'date_of_birth' => '2002-02-04',
                'nationality' => 'aze',
                'phone_number' => '114121 4 14 1',
                'gender_id' => 0,
                'country' => '1241 241 2412',
                'postal_code' => '1241',
                'city' => 'Baku',
                'national_chapter' => 2,
                'fb' => '23r 23r 23',
                'linkedin' => '23r',
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            1 =>
            array (
                'id' => 4,
                'first_name' => 'Muhammed',
                'email' => 'jasdj@asd.asd',
                'avatar' => 'images/2023-04-04/xhXbrB461OAFmTvPzaM6i9aO6Q8CLwVZ.jpeg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$r6xWtaaqL32vYzlN7VRBZOMjMyfB/d2Bnl2ydp62obSfPbr3KDjAK',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 09:10:30',
                'updated_at' => '2023-04-04 09:10:30',
                'username' => 'Codegac',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 0,
            ),
            2 =>
            array (
                'id' => 5,
                'first_name' => 'Muhammeds',
                'email' => 'jasdj@asd.asdsd',
                'avatar' => 'images/2023-04-04/ZnlB0AXcM4COk23To5aFB3mmsXVp9W05.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$a2Pq46I0Vd32gAOV0PfzT.aifHjy42V5TB0P2nzuwqr72Lk5pDl82',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 09:10:58',
                'updated_at' => '2023-04-04 09:10:58',
                'username' => 'Codegacs',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 0,
            ),
            3 =>
            array (
                'id' => 6,
                'first_name' => 'Muhammeds',
                'email' => 'jasdj@asd.asdsdx',
                'avatar' => 'images/2023-04-04/7NGyRbq9Osc3zmG1YXtZ3dilRIh8DwsD.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$gk5gY/x2j/FS7ohiNMkiJ.UuG6.aebBDJyBFr7L0huxRir.E0PhFe',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 10:38:24',
                'updated_at' => '2023-04-04 10:38:24',
                'username' => 'Codegacsx',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 0,
            ),
            4 =>
            array (
                'id' => 7,
                'first_name' => 'Muhammedss',
                'email' => 'jasdj@asd.asdsdxsd',
                'avatar' => 'images/2023-04-04/6FnumTI7xl5bao0SFysyzci6Z2U1kOdJ.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$xaDfansvHmlt.6I5Ku6mtOAxABryW0P2att.tGPAOm2dpeU2qk4Oq',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 10:40:09',
                'updated_at' => '2023-04-04 10:40:09',
                'username' => 'Codegacsxssd',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 0,
            ),
            5 =>
            array (
                'id' => 8,
                'first_name' => 'Muhammedqqesssdsdsa',
                'email' => 'jasdj@asd.assdsqdxsdsds',
                'avatar' => 'images/2023-04-04/tCn9dxlmLnYS7pixN7kN8XUbA7M2ivcd.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CYrtyEhIvZu48W2C3nMUIOHas5XW4fxCr1C6HbBzPGB4znM9GyPlC',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 10:49:28',
                'updated_at' => '2023-04-04 10:49:28',
                'username' => 'asdasdasdad',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 0,
            ),
            6 =>
            array (
                'id' => 9,
                'first_name' => 'asdasdasdssss',
                'email' => 'jasdj@asd.assdsqdxsdsdssss',
                'avatar' => 'images/2023-04-04/LJIueo4U4V6shI003Pt79PvrUbdZIyBd.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YI09OlB6QRWjMMPvCzBoOO3JcRIVIUEgvGSUytlCDlVm2qkUa4gPC',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 11:01:58',
                'updated_at' => '2023-04-04 11:01:58',
                'username' => 'asdasdasadadsdssss',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 0,
            ),
            7 =>
            array (
                'id' => 10,
                'first_name' => 'asdasdasdsssss',
                'email' => 'jasdj@asd.assdsqdxsdsdssssq',
                'avatar' => 'images/2023-04-04/4a2ukVCSIw7HRHmqe1mcV15P1D2WvDf1.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YFEJwMQIbePvE0RMTWEKL.TNMHEpgvSiVxkQen5QNMg0OEJYwcoG2',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 11:06:20',
                'updated_at' => '2023-04-04 11:06:20',
                'username' => 'asdasdasadadsdssssq',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 0,
            ),
            8 =>
            array (
                'id' => 11,
                'first_name' => 'asdasdasdssxcsss',
                'email' => 'jasdj@asd.assdsqdxsdsdssssqxc',
                'avatar' => 'images/2023-04-04/8WoeulTo2E6RVgWTVC63ak3AL5JoD0GB.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$eH0j/ltxFOo9wGi5cwE96ekXiGdavw/5qgQkE7orEMKmoNL4pyJqa',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 11:09:19',
                'updated_at' => '2023-04-04 11:09:19',
                'username' => 'asdasdasadadsdssssqxc',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            9 =>
            array (
                'id' => 12,
                'first_name' => 'asdasdasdssxcsss',
                'email' => 'jasdj@asd.assdsqdxsdsdssssqxcfd',
                'avatar' => 'images/2023-04-04/BEPzs1tjNA5t3nwmufKVD5GjaHP7yV9a.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$AD4cAhKQkFo0nisfJbiEiOmYa1uMB/cs8f1S2nDOeeXZhaCI/Gy4C',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 11:10:00',
                'updated_at' => '2023-04-04 11:20:48',
                'username' => 'asdasdasadadsdssssqxcdf',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            10 =>
            array (
                'id' => 13,
                'first_name' => 'sdsadsasdwe',
                'email' => 'jasdj@asd.assdsqdwessssqxcfd',
                'avatar' => 'images/2023-04-04/ayoRY6SJ8MdI54qOZnNGPnLm0ODKMu4f.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$vmJ89wU7ZQq4ALFKbtAWR.Nt3E0n24aR9YhIVnLe47eODaeHfIZ1m',
                'remember_token' => NULL,
                'created_at' => '2023-04-04 11:39:53',
                'updated_at' => '2023-04-04 11:39:53',
                'username' => 'wewewwewewewew',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => '2',
                'postal_code' => 'Az1000',
                'city' => '2',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            11 =>
            array (
                'id' => 14,
                'first_name' => 'sdsadsasdwes',
                'email' => 'jasdj@asd.assdsqdwessssqxcfds',
                'avatar' => 'images/2023-04-05/2wtULzVWVrDps1ZME7VG7Pk0gozUyHY1.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$MbIfT/CbJXnlm5Gx2ccv9eu1jp2wHNGtUn8oaXk52Tvnk8ug.JZMG',
                'remember_token' => NULL,
                'created_at' => '2023-04-05 05:04:43',
                'updated_at' => '2023-04-05 05:04:43',
                'username' => 'wewewwewewewews',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => 'asda',
                'postal_code' => 'Az1000',
                'city' => 'asdasd',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            12 =>
            array (
                'id' => 15,
                'first_name' => 'Muhammedqwe',
                'email' => 'fuadbayramli94@gmail.comw',
                'avatar' => 'images/2023-04-05/vtdd3t7iPNhnqPFa1ULKXYMscd1n2obi.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$KzWZ6pmayE0m6vn/CALNjeZWdIYgFtzGBnvAJt6kEf/Dvw5z7iiG6',
                'remember_token' => NULL,
                'created_at' => '2023-04-05 05:05:58',
                'updated_at' => '2023-04-05 05:05:58',
                'username' => 'Codegacqwe',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => 'qqwe',
                'postal_code' => 'Az1000',
                'city' => 'qweew',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => NULL,
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            13 =>
            array (
                'id' => 16,
                'first_name' => 'Muhammedqwe',
                'email' => 'fuadbayramli94@gmail.comws',
                'avatar' => 'images/2023-04-05/M2I2iiKF9vNTb8KuhrdWf8eTfbJkgAow.png',
                'email_verified_at' => NULL,
                'password' => '$2y$10$yOxDzSNAJW1yrAhhX.2OHu9J8KQD3L3L6a1Ul5enYzMgoEhHb0rFi',
                'remember_token' => NULL,
                'created_at' => '2023-04-05 05:07:14',
                'updated_at' => '2023-04-05 05:07:14',
                'username' => 'Codegacqwes',
                'nam_youth_email' => NULL,
                'last_name' => 'Mammadov',
                'date_of_birth' => '1989-12-10',
                'nationality' => 'Azerbaycanli',
                'phone_number' => '0556575878',
                'gender_id' => 1,
                'country' => 'qqwe',
                'postal_code' => 'Az1000',
                'city' => 'qweew',
                'national_chapter' => 1,
                'fb' => NULL,
                'linkedin' => NULL,
                'tw' => NULL,
                'ins' => 'adasdadasasdasdasdasdas',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
        ));


    }
}
