<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('menu_items')->delete();
        
        DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-boat',
                'id' => 1,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.dashboard',
                'target' => '_self',
                'title' => 'Dashboard',
                'updated_at' => '2023-04-03 06:16:19',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 15,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2023-06-21 16:40:13',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-person',
                'id' => 3,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2023-06-21 16:40:29',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-lock',
                'id' => 4,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2023-04-03 06:16:19',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-tools',
                'id' => 5,
                'menu_id' => 1,
                'order' => 19,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tools',
                'updated_at' => '2023-06-21 16:40:13',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-list',
                'id' => 6,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2023-04-11 04:58:55',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-data',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2023-04-11 04:58:55',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-compass',
                'id' => 8,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2023-04-11 04:58:55',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-bread',
                'id' => 9,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2023-04-11 04:58:55',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:19',
                'icon_class' => 'voyager-settings',
                'id' => 10,
                'menu_id' => 1,
                'order' => 20,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Settings',
                'updated_at' => '2023-06-21 16:40:13',
                'url' => '',
            ),
            10 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:20',
                'icon_class' => 'voyager-categories',
                'id' => 11,
                'menu_id' => 1,
                'order' => 18,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categories',
                'updated_at' => '2023-06-21 16:40:13',
                'url' => '',
            ),
            11 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:20',
                'icon_class' => 'voyager-news',
                'id' => 12,
                'menu_id' => 1,
                'order' => 16,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.posts.index',
                'target' => '_self',
                'title' => 'Posts',
                'updated_at' => '2023-06-21 16:40:13',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 06:16:20',
                'icon_class' => 'voyager-file-text',
                'id' => 13,
                'menu_id' => 1,
                'order' => 17,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.pages.index',
                'target' => '_self',
                'title' => 'Pages',
                'updated_at' => '2023-06-21 16:40:13',
                'url' => '',
            ),
            13 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-03 10:55:35',
                'icon_class' => 'voyager-world',
                'id' => 14,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.national-chapters.index',
                'target' => '_self',
                'title' => 'National Chapters',
                'updated_at' => '2023-06-21 16:40:29',
                'url' => '',
            ),
            14 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-04-03 12:44:47',
                'icon_class' => 'voyager-people',
                'id' => 15,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.members.index',
                'target' => '_self',
                'title' => 'Members',
                'updated_at' => '2023-06-21 16:40:29',
                'url' => '',
            ),
            15 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-11 09:26:07',
                'icon_class' => 'voyager-data',
                'id' => 16,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.countries.index',
                'target' => '_self',
                'title' => 'Countries',
                'updated_at' => '2023-06-21 16:40:29',
                'url' => '',
            ),
            16 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-11 09:55:10',
                'icon_class' => 'voyager-lock',
                'id' => 17,
                'menu_id' => 1,
                'order' => 12,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.member-roles.index',
                'target' => '_self',
                'title' => 'Member Roles',
                'updated_at' => '2023-06-21 16:40:19',
                'url' => '',
            ),
            17 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-13 08:01:35',
                'icon_class' => 'voyager-news',
                'id' => 18,
                'menu_id' => 1,
                'order' => 10,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.news.index',
                'target' => '_self',
                'title' => 'News',
                'updated_at' => '2023-06-21 16:40:29',
                'url' => '',
            ),
            18 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-17 07:30:58',
                'icon_class' => 'voyager-chat',
                'id' => 19,
                'menu_id' => 1,
                'order' => 11,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.contact-messages.index',
                'target' => '_self',
                'title' => 'Contact Messages',
                'updated_at' => '2023-06-21 16:40:29',
                'url' => '',
            ),
            19 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-17 12:48:22',
                'icon_class' => 'voyager-info-circled',
                'id' => 20,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 23,
                'route' => 'voyager.abouts.index',
                'target' => '_self',
                'title' => 'Abouts',
                'updated_at' => '2023-04-18 06:25:53',
                'url' => '',
            ),
            20 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-18 05:40:26',
                'icon_class' => 'voyager-file-text',
                'id' => 21,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 23,
                'route' => 'voyager.concepts.index',
                'target' => '_self',
                'title' => 'Concepts',
                'updated_at' => '2023-04-18 06:25:53',
                'url' => '',
            ),
            21 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-18 05:58:44',
                'icon_class' => 'voyager-lightbulb',
                'id' => 22,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 23,
                'route' => 'voyager.timelines.index',
                'target' => '_self',
                'title' => 'Timelines',
                'updated_at' => '2023-04-18 06:25:53',
                'url' => '',
            ),
            22 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-04-18 06:25:21',
                'icon_class' => 'voyager-documentation',
                'id' => 23,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Info',
                'updated_at' => '2023-04-18 06:27:49',
                'url' => '',
            ),
            23 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-25 10:38:57',
                'icon_class' => 'voyager-question',
                'id' => 24,
                'menu_id' => 1,
                'order' => 13,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.faqs.index',
                'target' => '_self',
                'title' => 'Faqs',
                'updated_at' => '2023-06-21 16:40:19',
                'url' => '',
            ),
            24 => 
            array (
                'color' => NULL,
                'created_at' => '2023-04-26 13:09:04',
                'icon_class' => 'voyager-bubble',
                'id' => 25,
                'menu_id' => 1,
                'order' => 14,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.testimonials.index',
                'target' => '_self',
                'title' => 'Testimonials',
                'updated_at' => '2023-06-21 16:40:19',
                'url' => '',
            ),
            25 => 
            array (
                'color' => NULL,
                'created_at' => '2023-05-19 11:09:30',
                'icon_class' => 'voyager-lightbulb',
                'id' => 27,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.opportunities.index',
                'target' => '_self',
                'title' => 'Opportunities',
                'updated_at' => '2023-06-21 16:40:29',
                'url' => '',
            ),
            26 => 
            array (
                'color' => NULL,
                'created_at' => '2023-06-05 15:31:51',
                'icon_class' => 'voyager-people',
                'id' => 29,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 23,
                'route' => 'voyager.board-secretariats.index',
                'target' => '_self',
                'title' => 'Board Secretariats',
                'updated_at' => '2023-06-05 15:52:37',
                'url' => '',
            ),
            27 => 
            array (
                'color' => NULL,
                'created_at' => '2023-06-05 15:49:38',
                'icon_class' => 'voyager-book',
                'id' => 30,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 23,
                'route' => 'voyager.projects.index',
                'target' => '_self',
                'title' => 'Projects',
                'updated_at' => '2023-06-05 15:52:47',
                'url' => '',
            ),
            28 => 
            array (
                'color' => NULL,
                'created_at' => '2023-06-21 16:02:34',
                'icon_class' => 'voyager-categories',
                'id' => 31,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 33,
                'route' => 'voyager.event-categories.index',
                'target' => '_self',
                'title' => 'Event Categories',
                'updated_at' => '2023-06-21 16:40:08',
                'url' => '',
            ),
            29 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-06-21 16:32:34',
                'icon_class' => 'voyager-calendar',
                'id' => 32,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 33,
                'route' => 'voyager.events.index',
                'target' => '_self',
                'title' => 'Events',
                'updated_at' => '2023-06-21 16:40:08',
                'url' => '',
            ),
            30 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-06-21 16:39:41',
                'icon_class' => 'voyager-calendar',
                'id' => 33,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Events',
                'updated_at' => '2023-06-21 16:40:29',
                'url' => '',
            ),
        ));
        
        
    }
}